1\) Conv2D and Corr2D Functions

In [25]:
import numpy as np

def sq_matrix_rot_180(X):
    res = np.zeros(X.shape, float)
    n = X.shape[0]
    for i in range(n):
        for j in range(n):
            res[i, j] = X[n-i-1, n-j-1]
    return res

def Conv2D(image, W): #stride 1, no padding
    W_rot = sq_matrix_rot_180(W)
    W_dim = W.shape[0]
    res_dim = image.shape[0] - W.shape[0] + 1
    res = np.zeros([res_dim, res_dim], float)
    for i in range(res_dim):
        for j in range(res_dim):
            res[i, j] = np.sum(W_rot*image[i:i+W_dim, j:j+W_dim])
    return res

def Corr2D(image, W): #stride 1, no padding
    W_dim = W.shape[0]
    res_dim = image.shape[0] - W.shape[0] + 1
    res = np.zeros([res_dim, res_dim], float)
    for i in range(res_dim):
        for j in range(res_dim):
            res[i, j] = np.sum(W*image[i:i+W_dim, j:j+W_dim])
    return res

Test

In [29]:
import scipy.signal as ss

def conv2Dd_(image,W,stride,Conv):
    if (Conv):
        y = ss.convolve2d(image, W, mode='valid') ## valid padding
    else:
        y = ss.correlate2d(image, W, mode='valid') ## valid padding
    Xdim = len(image[0])//stride
    x = np.zeros([Xdim,Xdim],float)
    if stride>1: ## implement stride
        for i in range(0,Xdim):
            for j in range(0,Xdim):
                x[i,j] = y[i*stride,j*stride]
    else:
        x = y
    return(x)

W = np.array([[1,2,3],[3,4,5],[6,7,8]],float)
image = np.zeros([7,7],float)
image[0,:] = np.array([0,0,0,0,0,0,0])
image[1,:] = np.array([0,0,0,0,0,0,0])
image[2,:] = np.array([0,0,0,0,0,0,0])
image[3,:] = np.array([0,0,0,1,0,0,0])
image[4,:] = np.array([0,0,0,0,0,0,0])
image[5,:] = np.array([0,0,0,0,0,0,0])
image[6,:] = np.array([0,0,0,0,0,0,0])

print("My Conv2D")
print(Conv2D(image, W))
print("My Corr2D")
print(Corr2D(image, W))
print("Scipy Conv2D")
print(conv2Dd_(image, W, 1, True))
print("Scipy Corr2D")
print(conv2Dd_(image, W, 1, False))


My Conv2D
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]
My Corr2D
[[0. 0. 0. 0. 0.]
 [0. 8. 7. 6. 0.]
 [0. 5. 4. 3. 0.]
 [0. 3. 2. 1. 0.]
 [0. 0. 0. 0. 0.]]
Scipy Conv2D
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]
Scipy Corr2D
[[0. 0. 0. 0. 0.]
 [0. 8. 7. 6. 0.]
 [0. 5. 4. 3. 0.]
 [0. 3. 2. 1. 0.]
 [0. 0. 0. 0. 0.]]
